services:
  backend:
    build:
      context: Backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/javataskmanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      ALLOWED_ORIGINS: https://javataskmanager.gsoltech.online,http://localhost:3000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: javataskmanager
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  db-data:

networks:
  app-network:
