# Etapa 1: Build do React
FROM node:22-alpine AS build
WORKDIR /app

# Configura permissões para evitar problemas em Linux
RUN adduser -D appuser && chown -R appuser /app
USER appuser

# Copia apenas os arquivos necessários para instalar dependências
COPY --chown=appuser:appuser package*.json ./

# Instala apenas as dependências necessárias para produção e limpa cache para reduzir uso de espaço
RUN npm ci --only=production --no-optional && npm cache clean --force

# Copia os demais arquivos e compila o projeto
COPY --chown=appuser:appuser . .
RUN npm run build

# Etapa 2: Configuração do Nginx
FROM nginx:stable-alpine

# Remove arquivos desnecessários do container para otimizar espaço
RUN rm -rf /etc/nginx/conf.d/*

# Copia os arquivos de build do React para o diretório padrão do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Copia o arquivo nginx.conf para configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expondo porta 80 para acesso
EXPOSE 80

# Inicia o servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
